### ISSUE TITLE
packages issue in nativescript app

### ISSUE THREAD

**Issue by fairking** [NickCis/simple-peerjs#2]
I am having some packages issues. 

if I put just the `simple-peerjs` as a dependency it complains about missing modules like `ws` and `wrtc`. But adding those dependencies doesn't solve the problem.

Is there anything missing? Does `simple-peerjs` require something else. Based on your node example it has nothing but `simple-peerjs`.

My repo is here: https://github.com/fairking/tns-peerjs/blob/main/app/components/Home.vue

**Comment by fairking** [comment]
The actual error I got is:
```
WARNING in ../node_modules/wrtc/lib/binding.js
Module not found: Error: Can't resolve '../build/Debug/wrtc.node' in 'C:\Code\tns-peerjs\node_modules\wrtc\lib'
 @ ../node_modules/wrtc/lib/binding.js
 @ ../node_modules/wrtc/lib/index.js
 @ ../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js

WARNING in ../node_modules/ws/lib/buffer-util.js
Module not found: Error: Can't resolve 'bufferutil' in 'C:\Code\tns-peerjs\node_modules\ws\lib'
 @ ../node_modules/ws/lib/buffer-util.js
 @ ../node_modules/ws/lib/receiver.js
 @ ../node_modules/ws/index.js
 @ ../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js

WARNING in ../node_modules/ws/lib/validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in 'C:\Code\tns-peerjs\node_modules\ws\lib'
 @ ../node_modules/ws/lib/validation.js
 @ ../node_modules/ws/lib/receiver.js
 @ ../node_modules/ws/index.js
 @ ../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js

ERROR in ../node_modules/node-fetch/lib/index.mjs 1039:21-25
"export 'default' (imported as 'http') was not found in 'http'
 @ ./components/Home.vue?vue&type=script&lang=ts& (../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&)
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js

ERROR in ../node_modules/node-fetch/lib/index.mjs 1406:56-60
"export 'default' (imported as 'http') was not found in 'http'
 @ ./components/Home.vue?vue&type=script&lang=ts& (../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&)
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js

ERROR in ../node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'net' in 'C:\Code\tns-peerjs\node_modules\ws\lib'
 @ ../node_modules/ws/lib/websocket.js 9:12-26
 @ ../node_modules/ws/index.js
 @ ../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js

ERROR in ../node_modules/ws/lib/websocket.js
Module not found: Error: Can't resolve 'tls' in 'C:\Code\tns-peerjs\node_modules\ws\lib'
 @ ../node_modules/ws/lib/websocket.js 11:12-26
 @ ../node_modules/ws/index.js
 @ ../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js

ERROR in ../node_modules/wrtc/build/Release/wrtc.node 1:2
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ../node_modules/wrtc/lib/binding.js 6:19-56
 @ ../node_modules/wrtc/lib/index.js
 @ ../node_modules/ts-loader??ref--6!../node_modules/vue-loader/lib??vue-loader-options!./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue?vue&type=script&lang=ts&
 @ ./components/Home.vue
 @ ./app.js
```

**Comment by NickCis** [comment]
Hi!

Are you building something for Node or just web?. If the idea is to use it on the web, you shouldn't add `ws`, `wrtc` or `node-fetch` (those modules are just node implementations for the web standards). You should install `simple-peerjs` and use it as the [web example shows](https://github.com/NickCis/simple-peerjs/blob/master/exmaples/web/src/index.js).

**Comment by fairking** [comment]
It is nativescript app. I guess it is nodejs. Not a web.

**Comment by NickCis** [comment]
So, you should replace the `node-fetch`, `ws` and `wrtc` with their native script implementations.

Does native script has a _fetch_, _web sockets_ and _webRTC_ implementations?

**Comment by fairking** [comment]
Thanks @NickCis 

Looks like I solved some of the issues by replacing the packages with NS ones.

But when I run the app I still have a bug:
```
System.err: TypeError: Cannot read property 'fd' of undefined
System.err: File: (file: node_modules\debug\src\node.js:154:28)
System.err:
System.err: StackTrace:
System.err: useColors(file: node_modules\debug\src\node.js:154:28)
System.err:     at createDebug(file: node_modules\debug\src\common.js:119:32)
System.err:     at (file: node_modules\simple-peer\index.js:2:29)
System.err:     at ../node_modules/simple-peer/index.js(file:///data/data/org.nativescript.tns_peerjs/files/app/vendor.js:108187:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/simple-peerjs/src/ConnectionManager.js(file: node_modules\simple-peerjs\src\ConnectionManager.js:2:13)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/simple-peerjs/src/index.js(file: node_modules\simple-peerjs\src\index.js:1:17)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ../node_modules/ts-loader/index.js?!../node_modules/vue-loader/lib/index.js?!./components/Home.vue?vue&type=script&lang=ts&(file: app\components\Home.vue?57c6:1:0)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ./components/Home.vue?vue&type=script&lang=ts&(file: app\components\Home.vue?c1ac:1:0)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at ./components/Home.vue(file: app\components\Home.vue:1:0)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at fn(file: app\webpack\bootstrap:120:0)
System.err:     at (file: app\app.js:1:0)
System.err:     at ./app.js(file:///data/data/org.nativescript.tns_peerjs/files/app/bundle.js:1245:30)
System.err:     at __webpack_require__(file: app\webpack\bootstrap:816:0)
System.err:     at checkDeferredModules(file: app\webpack\bootstrap:43:0)
System.err:     at webpackJsonpCallback(file: app\webpack\bootstrap:30:0)
System.err:     at (file:///data/data/org.nativescript.tns_peerjs/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
```

Does Anybody know what might be an issue?

The repo is here: https://github.com/fairking/tns-peerjs/blob/main/app/components/Home.vue

**Comment by NickCis** [comment]
I really don't known what is that `fd` property which triggers the error. I've never use nativescript, so I really don't know, what is the line that is triggering the error?. Have you passed the websocket, webrtc and fetch implementations? (Does native script provide implementations for those web apis?).

**Comment by fairking** [comment]
@NickCis >
> > Have you passed the websocket, webrtc and fetch implementations? (Does native script provide implementations for those web apis?).

You can see by yourself. The `fetch` one is a native script built-in implementation (https://docs.nativescript.org/ns-framework-modules/fetch).
![image](https://user-images.githubusercontent.com/13495631/98648732-90d0c180-232e-11eb-9ad1-7149dfecf2db.png)

**Comment by NickCis** [comment]
As I've said previously, I'm not a NativeScript user, so I really don't know what is happening there.

**Comment by fairking** [comment]
Thanks for your help. Maybe someone else is also trying to implement peerjs in ns.
