### ISSUE TITLE
`fetch` is not defined

### ISSUE THREAD

**Issue by nolash** [NickCis/simple-peerjs#3]
Have:

```
const SimplePeerJs = require('simple-peerjs');


async function main() {
	const f = new SimplePeerJs(foo');
	const c = await f.connect('bar', {
		host: 'localhost',
		port: 9999,
	});
	c.peer.send('xyzzy');
}

main();
```

get:

```
$ node test.js 
(node:834227) UnhandledPromiseRejectionWarning: ReferenceError: fetch is not defined
    at new Api (/home/lash/src/tests/peerjs/js/simplepeerjs/node_modules/simple-peerjs/src/Api.js:6:42)
    at new Signaler (/home/lash/src/tests/peerjs/js/simplepeerjs/node_modules/simple-peerjs/src/Signaler.js:62:17)
    at new ConnectionManager (/home/lash/src/tests/peerjs/js/simplepeerjs/node_modules/simple-peerjs/src/ConnectionManager.js:21:21)
    at main (/home/lash/src/tests/peerjs/js/simplepeerjs/test.js:5:12)
    at Object.<anonymous> (/home/lash/src/tests/peerjs/js/simplepeerjs/test.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
```

Tried to install `node-fetch`. didn't make a difference.

* package: https://g33k.holbrook.no/0fda57a0

```
$ node --version
v14.14.0
```

**Comment by NickCis** [comment]
As the [readme](https://github.com/NickCis/simple-peerjs#in-node) says (and the [example](https://github.com/NickCis/simple-peerjs/blob/master/exmaples/node/initiator.js#L13) points out), you should install `wrtc`, `node-fetch` and `ws` and pass them as options to the `SimplePeerJs` class:

```js
const wrtc = require('wrtc');
const fetch = require('node-fetch');
const WebSocket = require('ws');
const SimplePeerJs = require('simple-peerjs');

const peer = new SimplePeerJs({
  wrtc,
  fetch,
  WebSocket,
})
```

**Comment by nolash** [comment]
right you are, sorry
